### ISSUE TITLE
How can get ico files from exe?

### ISSUE THREAD

**Issue by iwind** [folbricht/pefile#1]
Hi, thanks for your great work! And i have a question, how can get ico files from exe? GetResources() method only return a name and data, i don't know the file's type.

**Comment by folbricht** [comment]
IIRC, the type of the file is part of its "path" which you can see with the `list-resources` subcommand. You might see something like this

```
pefile list-resources myfile.exe
3/1/1033
3/2/1033
3/3/1033
3/4/1033
3/5/1033
14/IDI_APPICON/1033
16/1/1033
24/1/1033
```

The format of that is <type>/<ID>/<Language>, with type=3 being ICON group and 14 APPICON.

**Comment by iwind** [comment]
> IIRC, the type of the file is part of its "path" which you can see with the `list-resources` subcommand. You might see something like this
> 
> ```
> pefile list-resources myfile.exe
> 3/1/1033
> 3/2/1033
> 3/3/1033
> 3/4/1033
> 3/5/1033
> 14/IDI_APPICON/1033
> 16/1/1033
> 24/1/1033
> ```
> 
> The format of that is //, with type=3 being ICON group and 14 APPICON.

Thank you!
